import type { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import CssBaseline from "@mui/material/CssBaseline";
import AppBar from "@mui/material/AppBar";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import ColorModeSwitcher from "@/components/color-mode-switcher";
import "@mui/material-pigment-css/styles.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Material UI x Pigment CSS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ja">
      <body className={roboto.variable}>
        <CssBaseline />
        <AppBar variant="elevation" position="sticky">
          <Toolbar>
            <Typography component="h1">
              Pigment CSS + Next.js App Router
            </Typography>
            <div sx={{ flexGrow: 1 }} />
            <ColorModeSwitcher />
          </Toolbar>
        </AppBar>
        {children}
      </body>
    </html>
  );
}
