import type { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import CssBaseline from "@mui/material/CssBaseline";
import { LayoutStoreProvider } from "@/providers/layout-store-provider";
import AppBar from "@/components/layout/appbar";
import Drawer from "@/components/layout/drawer";
import Fab from "@/components/layout/fab";
import "@mui/material-pigment-css/styles.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Material UI x Pigment CSS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ja">
      <body className={roboto.variable}>
        <CssBaseline />
        <LayoutStoreProvider>
          <AppBar />
          {children}
          <Drawer />
          <div sx={{ position: "fixed", bottom: 16, right: 16, zIndex: "fab" }}>
            <Fab />
          </div>
        </LayoutStoreProvider>
      </body>
    </html>
  );
}
